<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Fin_Habilitation</name>
   <tag></tag>
   <elementGuidId>5b4740e1-4d82-496f-a28b-59f62e36c384</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='v-dbtdhtmlxHAB']/table/tbody//td[3][text()='${textHAB}']//following-sibling::td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
